{
 "title": "Cluster Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "# GPUs Unused",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "4" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=~\"apiserver|kubernetes-apiservers\"} == 1) / count(up{job=~\"apiserver|kubernetes-apiservers\"})) * 96"
    }
   ]
  },
  {
   "title": "FlashBlade Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "purefb_perf_nfs_rd_latency_usec",
     "legendFormat": "Read (microsec)"
    },
    {
     "expr": "purefb_perf_nfs_wr_latency_usec",
     "legendFormat": "Write (microsec)"
    },
    {
     "expr": "purefb_perf_nfs_others_latency_usec",
     "legendFormat": "Other (microsec)"
    }
   ]
  },
  {
   "title": "FlashBlade IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "purefb_perf_nfs_rd_ops", "legendFormat": "Read" },
    { "expr": "purefb_perf_nfs_wr_ops", "legendFormat": "Write" },
    { "expr": "purefb_perfnfs_others_ops", "legendFormat": "Other" }
   ]
  },
  {
   "title": "FlashBlade Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "purefb_perf_nfs_rd_bps", "legendFormat": "Read" },
    { "expr": "purefb_perf_nfs_wr_bps", "legendFormat": "Write" }
   ]
  },
  {
   "title": "FlashBlade Avg. IO Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "purefb_perf_nfs_bytes_per_read", "legendFormat": "Read" },
    {
     "expr": "purefb_perf_nfs_bytes_per_write",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Kubernetes Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal)) * 100"
    }
   ]
  },
  {
   "title": "Kubernetes Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size{device!=\"rootfs\"}) - sum(node_filesystem_free{device!=\"rootfs\"})) / sum(node_filesystem_size{device!=\"rootfs\"})"
    }
   ]
  }
 ]
}