{
 "title": "FlashBlade Client Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Client Metadata IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "purefb_clients_others_ops", "legendFormat": "{{name}}" },
    {}
   ]
  },
  {
   "title": "Client Read IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "purefb_clients_read_bps", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Client Write IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "purefb_clients_write_ops", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Client Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "purefb_clients_others_latency_usec",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "purefb_clients_read_latency_usec",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "purefb_clients_write_latency_usec",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}